version: '3.8'


# run in the server not in the devcontainer
services:
  # endpoint=http://member-sv-setting:5000/api
  # need to use api port not the container port
  nginx-proxy:
    image: nginx
    restart: unless-stopped

    ports:
      - "5000:80"

    volumes:
      - ./nginx:/etc/nginx/conf.d

    # environment:
    #   - VIRTUAL_HOST=dotnetapi.com

    networks:
      - default
    
  member-sv:
    image: 13angs/dotnetbs-member-sv:latest
    container_name: member-sv
    build:
      context: ../../member-service
      dockerfile: Dockerfile
    
    networks:
      - default

  member-sv-setting:
    image: 13angs/dotnetbs-member-sv-setting:latest
    container_name: member-sv-setting
    build:
      context: ../../member-sv-setting
      dockerfile: Dockerfile

    networks:
      - default

networks:
  default:
    name: compose_default