version: '3.8'

services:
  # endpoint=http://member-sv-setting:5000/api
  # need to use api port not the container port
  member-sv:
    image: 13angs/dotnetbs-member-sv:latest
    container_name: member-sv
    build:
      context: ../../member-service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    
    networks:
      - default

  member-sv-setting:
    image: 13angs/dotnetbs-member-sv-setting:latest
    container_name: member-sv-setting
    build:
      context: ../../member-sv-setting
      dockerfile: Dockerfile
    ports:
      - "5002:5000"

    networks:
      - default

networks:
  default:
    name: compose_default