version: '3.8'

services:
  dotnetbs-email-sender:
    image: 13angs/dotnetbs-email-sender:latest
    container_name: dotnetbs-email-sender
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        - "VARIANT=6.0-bullseye"
        - "NODE_VERSION=lts/*"
    
    volumes:
      - ../..:/workspaces/dotnetcore-basic:cached
      - /var/run/docker.sock:/var/run/docker.sock
    
    command: sleep infinity