version: '3.8'

services:
  dotnetbs-ms-rabbitmq:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        - "VARIANT=6.0-bullseye"
        - "NODE_VERSION=lts/*"
    
    volumes:
      - ../..:/workspaces/dotnetcore-basic:cached
      - /var/run/docker.sock:/var/run/docker.sock

    command: sleep infinity

    networks:
      - dotnetbs-network

networks:
  dotnetbs-network:
    name: dotnetbs-network
    external: true