version: '3.8'

services:
  dbs-nx-fullstack-user-sv:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - "VARIANT=6.0-bullseye"
        - "NODE_VERSION=lts/*"
    container_name: dbs-nx-fullstack-user-sv-devcon-${OWNER}

    volumes:
      - ../..:/workspaces/dotnetcore-basic:cached
      - /var/run/docker.sock:/var/run/docker.sock

    command: sleep infinity
    networks:
      - dbs-nx-fullstack-network

networks:
  dbs-nx-fullstack-network:
    external: true
    name: dbs-nx-fullstack-network